name: "newsApp"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  bloc: ^8.1.0
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  hexcolor: ^2.0.7
  shared_preferences: ^2.0.15
  webview_flutter: ^3.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
